apiVersion: v1
kind: Pod
metadata:
    name: clearsessions
    labels:
        app: clearsessions
spec:
    containers:
        - name: django-clearsessions
          image: django_app:latest
          imagePullPolicy: IfNotPresent
          command: ["python"]
          args: ["manage.py", "clearsessions"]
          envFrom:
              - configMapRef:
                    name: my-web-config
    restartPolicy: Never
